### ISSUE TITLE
USER STORY: Deploy a project

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/ukrainian-cafe#1]
EPIC: Deployment

As a **Developer** I can **deploy my project early** so that **I can avoid technical issues and reduce stress before deadline**

**Acceptance Criteria**
- The project must be deployed to Heroku
- The project must use Cloudinary to host images 
- The code must be stored in GitHub
- The project must be displayed through GitHub

**Tasks**
- [x] Create workspace with Gitpod
- [x] Install Django and gunicorn
- [x] Install Cloudinary
- [x] Create Project
- [x] Create a new external database
- [x] Create the Heroku app
- [x] Attach the database
- [x] Prepare environment and setting.py file
- [x] Get static and media files stored on Cloudinary
