### ISSUE TITLE
USER STORY: Update today's specials

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/ukrainian-cafe#14]
EPIC: Menu

As a **Business Owner** I can **update today's specials** so that **customers can see our recommendations**

**Acceptance Criteria**
- Business Owner should be able to create, update or delete today's specials on admin panel
- Business Owner should be able to add title, description and image

**Tasks**
- [x] Create Specials model
- [x] Create Specials view
- [x] Create template 
- [x] Wire urls
- [x] Test by adding three items with title, description and image
