### ISSUE TITLE
USER STORY: Edit or delete today's specials

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/ukrainian-cafe#15]
EPIC: Menu

As a **Business Owner** I can **edit or delete today's specials** so that **we can present relevant information**

**Acceptance Criteria**
- Business Owner can edit or delete specials items on front end

**Tasks**
- [ ] Create today specials html
- [ ] Add function to render today specials html template
- [ ] Create form to add specials on front end
- [ ] Add CRUD functionality
