### ISSUE TITLE
USER STORY: User registration and login

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/ukrainian-cafe#6]
EPIC: Login

As a **Site User** I can **register or login the website** so that **I can book a table**

**Acceptance Criteria**
- Site User should be able to register the website by typing in username, password and email
- Registered user should be able to login the website by typing their username and password 

**Tasks**
- [x] Create a Customer model
- [ ] Create profile html
- [x] Install AllAuth library
- [x] Manage URLs
- [x] Customize HTML templates for signup, login and logout

**Comment by konstanciaa** [comment]
Profile page is a feature to implement in the future
