### ISSUE TITLE
USER STORY: Booking a table

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/ukrainian-cafe#7]
EPIC: Booking

As a **Site User** I can **fill out a booking form** so that **I book a table for a certain date and time**

**Acceptance Criteria**
- Registered user should be able to fill out the booking form
- Booking form should take the following information: user's first name and last name, contact details (email and phone number), booking date and time, number of people

**Tasks**
- [x] Create booking model
- [x] Create booking html file
- [x] Style booking form
